# Generated by Django 5.0.5 on 2024-05-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_quantity_alter_item_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isNew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='isSale',
            field=models.BooleanField(default=False),
        ),
    ]
