# Generated by Django 5.0.5 on 2024-05-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_isnew_item_issale'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isBestseller',
            field=models.BooleanField(default=False),
        ),
    ]
